image: moussavdb/yildiz-build-image

pipelines:
  default:
    - step:
        script:
          - mvn -V -B -s settings.xml org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=$SONAR_ORGANIZATION -Dsonar.login=$SONAR
